server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/********
          search-paths: '{application}'
          default-label: develop
          clone-on-start: true
          force-pull: true
          username: ******
          password: *****
management:
  endpoints:
    web:
      exposure:
        include: health, env, refresh
  endpoint:
    health:
      show-details: always
